version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    container_name: flask-api
    environment:
      # Please update this with OMDB API Key
      # http://www.omdbapi.com/apikey.aspx
    - OMDB_APIKEY=<APIKEY>
    networks:
     - internal
  vue:
    build:
      context: ./ML_MovieRecommender_Vue
      dockerfile: Dockerfile_vue
      args: 
        # For deployment pass actual API Endpoint here
        # Vue env value will be overwritten with this value
        - VUE_APP_API_URL=http://localhost:5000
    ports:
     - "80:80"
    depends_on:
      - flask
    networks:
     - internal

networks:
  internal:
    driver: bridge

